name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '21'
      ANDROID_API_LEVEL: 34
      ANDROID_BUILD_TOOLS_VERSION: 34.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3


      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Run tests
        id: test
        run: ./gradlew test
        continue-on-error: true

      - name: Upload test reports
        if: ${{ failure() || steps.test.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            **/build/reports/tests/
            **/build/reports/androidTests/
            **/build/test-results/
          retention-days: 7

      - name: Check test results
        if: ${{ steps.test.outcome == 'failure' }}
        run: exit 1

      - name: Build app
        if: success()
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign_app
        uses: ilharp/sign-android-release@nightly
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*signed.apk