name: Publish to Play Store

on:
  workflow_dispatch:
    inputs:
      track:
        description: "Play Store track"
        required: true
        default: "internal"
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Play Store service account
        run: echo "$PLAY_STORE_JSON_KEY" > play-store-key.json
        env:
          PLAY_STORE_JSON_KEY: ${{ secrets.PLAY_STORE_JSON_KEY }}

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign APK
        id: sign_app
        uses: ilharp/sign-android-release@nightly
        with:
          releaseDir: app/build/outputs/bundle/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}


      - name: Upload APK artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/*signed.aab

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: play-store-key.json
          packageName: com.paulcoding.pindownloader
          releaseFiles: app/build/outputs/bundle/release/*signed.aab
          track: ${{ github.event.inputs.track }}