name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '21'
      ANDROID_API_LEVEL: 34
      ANDROID_BUILD_TOOLS_VERSION: 34.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate key.properties
        run: |
          echo "$KEY_PROPERTIES" > key.properties
          chmod 600 key.properties
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build app
        run: ./gradlew assembleRelease

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          includeInvalidCommits: true
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: ${{ steps.changelog.outputs.changes }}
          files: app/build/outputs/apk/release/*.apk
          fail_on_unmatched_files: true
          make_latest: true